package com.sahiwal.mykotlinpract

enum class MyEnums {
    WEEK,MONTH,YEAR,
    SUNDAY,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATUREDAY,

    JAN,FEB,MARCH,APRIL,MAY,JUN,JULY,AUG,SEPT,OCT,NOV,DEC
}